# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

a = np.random.random((3,3,3))
a

array([[[0.82511565, 0.50157992, 0.31114549],
        [0.00210691, 0.06096688, 0.85494077],
        [0.35744246, 0.61390942, 0.34881408]],

       [[0.43835248, 0.13539883, 0.4649369 ],
        [0.58290913, 0.62204025, 0.3256297 ],
        [0.22772031, 0.24767279, 0.18443119]],

       [[0.94142317, 0.43403344, 0.45341687],
        [0.23088904, 0.25875451, 0.92625263],
        [0.85914273, 0.93134596, 0.7210098 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
a = np.diag([1, 2, 3, 4, 5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
def chk_brd(n): 
    result = [] 
    for i in range(n): 
        result.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2)))) 
    print(np.array(result)) 
  

n = 8

chk_brd(n) 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
x= np.random.random((5,5))
print("Original matrix:\n")
print(x)

x_max, x_min = x.max(), x.min()

x = (x - x_min)/(x_max - x_min)
print("\nNormalized matrix:\n")

print(x)

Original matrix:

[[0.54047339 0.02104684 0.07562123 0.58271555 0.22974963]
 [0.96503441 0.34661553 0.98138169 0.03833675 0.08828556]
 [0.81223811 0.85929358 0.66881282 0.44696858 0.98290425]
 [0.44100696 0.35366251 0.75069902 0.8009693  0.94338594]
 [0.88531349 0.41668338 0.06274787 0.6076811  0.37815412]]

Normalized matrix:

[[0.54002448 0.         0.05673855 0.58394177 0.21697894]
 [0.98142153 0.33847916 0.99841706 0.01797555 0.06990509]
 [0.82256607 0.87148753 0.67345323 0.44281173 1.        ]
 [0.4366137  0.34580559 0.75858664 0.81085039 0.95891459]
 [0.89853926 0.41132556 0.04335469 0.60989732 0.37126842]]


# 5.  How to find common values between two arrays?

In [5]:
a1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",a1)

a2 = [10, 30, 40]
print("Array2: ",a2)

print("\nCommon values between two arrays are:")
print(np.intersect1d(a1, a2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]

Common values between two arrays are:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import datetime 

today = datetime.date.today()

yesterday = today - datetime.timedelta(days = 1)

tomorrow = today + datetime.timedelta(days = 1) 

print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)


Yesterday :  2020-07-27
Today :  2020-07-28
Tomorrow :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
def Equal(a1, a2, x, y):
    if (x != y): 
        return False; 
  
    a1.sort(); 
    a2.sort(); 
  
    for i in range(0, x - 1): 
        if (a1[i] != a2[i]):
            return False;
  
    
    return True; 

a1 = [1,2,6,4,7]; 
a2 = [2,4,7,6,1]; 
x = len(a1); 
y = len(a2); 
  
if (Equal(a1, a2, x, y)): 
    print("Arrays are equal"); 
else: 
    print("Arrays are not equal to each other"); 


Arrays are equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
a = np.random.random(10)
print("Original array:\n")
print(a)

a[a.argmax()] = 0
print("\nMaximum value replaced by 0:\n")
print(a)

Original array:

[0.83985672 0.8186399  0.09373961 0.11653132 0.88210355 0.08743134
 0.86580652 0.34731652 0.87986818 0.76451162]

Maximum value replaced by 0:

[0.83985672 0.8186399  0.09373961 0.11653132 0.         0.08743134
 0.86580652 0.34731652 0.87986818 0.76451162]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")

X = np.random.rand(4,4)
print(X)

print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.51224165 0.20049259 0.93697945 0.59073375]
 [0.17077423 0.96446628 0.44028328 0.69852251]
 [0.95027379 0.71201703 0.16699249 0.39439316]
 [0.92354246 0.19490712 0.37737624 0.28834894]]

Subtract the mean of each row of the said matrix:

[[-0.04787021 -0.35961927  0.37686759  0.03062189]
 [-0.39773734  0.39595471 -0.1282283   0.13001093]
 [ 0.39435467  0.15609791 -0.38892663 -0.16152596]
 [ 0.47749877 -0.25113657 -0.06866745 -0.15769475]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
a = np.ones(5)
b = np.random.randint(0,len(a),10)
a += np.bincount(b, minlength=len(a))
print(a)


np.add.at(a, b, 1)
print(a)

[1. 5. 3. 5. 1.]
[1. 9. 5. 9. 1.]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np
a = [1,7,6]
b = [4,5,9]
dot_product = np.dot(a,b)
print('Dot product is : ' , dot_product)

Dot product is :  93


# 13.How to find the most frequent value in an array?

In [13]:
import statistics 

from statistics import mode 
  
def most_common(List): 
    return(mode(List)) 
    
List = [1,4,2,3,4,3,6,3,4,1,7,3,5,4,9,4] 
print(most_common(List)) 


4


# 14.How to get the n largest values of an array

In [14]:
a = np.arange(10)
print("Original array:")
print(a)
np.random.shuffle(a)
n = 1
print (a[np.argsort(a)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [15]:
a1 = np.array([("Delhi", 10000, 150000),
                 ("Bihar", 13000, 15000),
             ("Tamil Nadu", 54000, 150000)])
print("Original arrays:")
print(a1)

print("\nRecord array:\n")
result = np.core.records.fromarrays(a1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Delhi' '10000' '150000']
 ['Bihar' '13000' '15000']
 ['Tamil Nadu' '54000' '150000']]

Record array:

[(b'Delhi', 10000., 150000) (b'Bihar', 13000.,  15000)
 (b'Tamil Nadu', 54000., 150000)]
